'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowHeader() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowHeader"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowHeader") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowSuppressedProperties() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowSuppressedProperties"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowSuppressedProperties") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowClasses() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowClasses"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowClasses") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowObjects() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowObjects"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowObjects") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowCurrentDimstlye() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowCurrentDimstlye"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowCurrentDimstlye") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowInstances() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowInstances"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowInstances") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowHiddenProperties() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowHiddenProperties"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowHiddenProperties") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTables() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTables"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTables") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowEntities() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowEntities"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowEntities") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowScreenSettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowScreenSettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowScreenSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowDimSettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowDimSettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowDimSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowLTLSettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowLTLSettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowLTLSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTableSettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableSettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTextSettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTextSettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTextSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowDisplaySettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowDisplaySettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowDisplaySettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowDimOverrideSettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowDimOverrideSettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowDimOverrideSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowSymbolSettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowSymbolSettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowSymbolSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PropertyViewer_ShowBlocks() As String
            Get
                Return CType(Me("PropertyViewer_ShowBlocks"),String)
            End Get
            Set
                Me("PropertyViewer_ShowBlocks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PropertyViewer_ShowHiddenObjects() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowHiddenObjects"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowHiddenObjects") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTableVPORTS() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableVPORTS"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableVPORTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PropertyViewer_ShowTableLTYPES() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableLTYPES"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableLTYPES") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PropertyViewer_ShowTableLAYERS() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableLAYERS"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableLAYERS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PropertyViewer_ShowTableSTYLES() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableSTYLES"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableSTYLES") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTableVIEWS() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableVIEWS"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableVIEWS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTableUCSS() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableUCSS"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableUCSS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTableAPPIDS() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableAPPIDS"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableAPPIDS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTableDIMSTYLES() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableDIMSTYLES"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableDIMSTYLES") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowTableBLOCKRECORDS() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowTableBLOCKRECORDS"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowTableBLOCKRECORDS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_ShowSettings() As Boolean
            Get
                Return CType(Me("PropertyViewer_ShowSettings"),Boolean)
            End Get
            Set
                Me("PropertyViewer_ShowSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ProperyViewer_WorkingFolder() As String
            Get
                Return CType(Me("ProperyViewer_WorkingFolder"),String)
            End Get
            Set
                Me("ProperyViewer_WorkingFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PropertyViewer_SuppressDimOverrides() As Boolean
            Get
                Return CType(Me("PropertyViewer_SuppressDimOverrides"),Boolean)
            End Get
            Set
                Me("PropertyViewer_SuppressDimOverrides") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.My.MySettings
            Get
                Return Global.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
